spring.application.name=Smart-Fridge

# Import the .env file from the root directory
spring.config.import=optional:file:.env[.properties]

# Map Spring datasource properties to the .env variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=8081
server.address=0.0.0.0

logging.file.name=spring_errors.log

spring.main.banner-mode=off
logging.level.root=warn

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
